Importing libraries

In [77]:
import pandas as pd
import numpy as np

Reading CSV file

In [78]:
df=pd.read_csv("ecommerce_sales_data.csv")
print(df)

      ID  Customer_Name   Order_ID  Order_Date        Product     Category  \
0    100   Customer_100  ORD-41285  11/22/2024        Blender         Home
1    101   Customer_101  ORD-35783    7/5/2025     Smartphone  Electronics
2    102   Customer_102  ORD-84355  12/23/2024  Tennis Racket       Sports
3    103   Customer_103  ORD-57811   3/19/2025        Science        Books
4    104   Customer_104  ORD-93614  10/20/2025      Biography        Books
..   ...            ...        ...         ...            ...          ...
98   198   Customer_198  ORD-14608   7/27/2025         Vacuum          NaN
99   199   Customer_199  ORD-82922   1/22/2025        Blender         Home
100  175   Customer_175  ORD-56651   2/24/2025     Headphones  Electronics
101  142   Customer_142  ORD-69018  10/30/2025          Shoes     Clothing
102  146   Customer_146  ORD-32755    7/9/2025     Basketball   electronic

    Quantity   Price    Payment_Method      Status     Total
0          3      38  Cash on Delivery     Shipped   114.000
1          2     abd            PayPal  Processing       NaN
2          1  389.05            PayPal   Delivered   389.050
3          5  233.92            PayPal  Processing  1169.600
4          1  552.51  Cash on Delivery  Processing   552.510
..       ...     ...               ...         ...       ...
98         2  497.01  Cash on Delivery     Shipped   994.020
99         5  372.28       Credit Card     Shipped  1861.400
100        1  111.36       Credit Card  Processing    77.952
101        5  645.26       Credit Card     Shipped  3226.300
102        2  705.42     Bank Transfer  Processing  1410.840

[103 rows x 11 columns]


Displaying Columns name

In [79]:
print(df.columns.tolist())

['ID', ' Customer_Name', 'Order_ID', 'Order_Date', 'Product', ' Category', 'Quantity', 'Price', 'Payment_Method', 'Status', 'Total']

Remove spaces ,Capitalize columns name and replace "_" to " "

In [80]:
df.columns=df.columns.str.strip().str.capitalize().str.replace("_"," ")
print(df.columns.tolist)

<bound method IndexOpsMixin.tolist of Index(['Id', 'Customer name', 'Order id', 'Order date', 'Product', 'Category',
       'Quantity', 'Price', 'Payment method', 'Status', 'Total'],
      dtype='str')>

Checking duplicate Columns

In [81]:
print(len(df.columns))
print(len(df.columns.unique()))
print(df.info())

11
11
<class 'pandas.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Id              103 non-null    int64
 1   Customer name   103 non-null    str
 2   Order id        103 non-null    str
 3   Order date      103 non-null    str
 4   Product         103 non-null    str
 5   Category        95 non-null     str
 6   Quantity        98 non-null     str
 7   Price           98 non-null     str
 8   Payment method  103 non-null    str
 9   Status          103 non-null    str
 10  Total           89 non-null     float64
dtypes: float64(1), int64(1), str(9)
memory usage: 9.0 KB
None

Analysing dataset-info & sum of null values in dataset

In [82]:
print(df.info())
print(df.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Id              103 non-null    int64
 1   Customer name   103 non-null    str
 2   Order id        103 non-null    str
 3   Order date      103 non-null    str
 4   Product         103 non-null    str
 5   Category        95 non-null     str
 6   Quantity        98 non-null     str
 7   Price           98 non-null     str
 8   Payment method  103 non-null    str
 9   Status          103 non-null    str
 10  Total           89 non-null     float64
dtypes: float64(1), int64(1), str(9)
memory usage: 9.0 KB
None
Id                 0
Customer name      0
Order id           0
Order date         0
Product            0
Category           8
Quantity           5
Price              5
Payment method     0
Status             0
Total             14
dtype: int64

Cleaning column "Order date"

In [83]:
#checking data type of column "Order date"
print(df["Order date"].dtype)
#changing datatype (str to datetime)
df["Order date"] = pd.to_datetime(df["Order date"],errors="coerce")
print("\nFix Applied")
#checking data type
print(df["Order date"].dtype)
#displaying the column
print(df["Order date"])
#checking dataset-info()
print(df.info())
#droping null valeu rows
df=df.dropna(subset="Order date")
#checking sum of null values in column
print(df["Order date"].isnull().sum())

str

Fix Applied
datetime64[us]
0     2024-11-22
1     2025-07-05
2     2024-12-23
3     2025-03-19
4     2025-10-20
         ...
98    2025-07-27
99    2025-01-22
100   2025-02-24
101   2025-10-30
102   2025-07-09
Name: Order date, Length: 103, dtype: datetime64[us]
<class 'pandas.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Id              103 non-null    int64
 1   Customer name   103 non-null    str
 2   Order id        103 non-null    str
 3   Order date      101 non-null    datetime64[us]
 4   Product         103 non-null    str
 5   Category        95 non-null     str
 6   Quantity        98 non-null     str
 7   Price           98 non-null     str
 8   Payment method  103 non-null    str
 9   Status          103 non-null    str
 10  Total           89 non-null     float64
dtypes: datetime64[us](1), float64(1), int64(1), str(8)
memory usage: 9.0 KB
None
0

Rows sorted ,the small charater word are sorted in last

In [84]:
nf=np.sort(df["Product"].unique())
nf

array(['Basketball', 'Biography', 'Blender', 'Comics', 'Fiction',
       'Football', 'Headphones', 'Jacket', 'Jeans', 'Lamp', 'Laptop',
       'Microwave', 'Science', 'Shoes', 'Smartphone', 'Smartwatch',
       'T-shirt', 'Tennis Racket', 'Vacuum', 'Yoga Mat', 'shoes'],
      dtype=object)

Cleaning Product Column

In [85]:
print(df["Product"].unique())
df["Product"]=df["Product"].str.replace("shoes","Shoes")
print("\nFixed Applied")
print(df["Product"].unique())

<StringArray>
[      'Blender',    'Smartphone', 'Tennis Racket',       'Science',
     'Biography',    'Basketball',        'Comics',         'Shoes',
       'Fiction',     'Microwave',      'Yoga Mat',        'Vacuum',
          'Lamp',       'T-shirt',    'Smartwatch',    'Headphones',
      'Football',        'Laptop',        'Jacket',         'shoes',
         'Jeans']
Length: 21, dtype: str

Fixed Applied
<StringArray>
[      'Blender',    'Smartphone', 'Tennis Racket',       'Science',
     'Biography',    'Basketball',        'Comics',         'Shoes',
       'Fiction',     'Microwave',      'Yoga Mat',        'Vacuum',
          'Lamp',       'T-shirt',    'Smartwatch',    'Headphones',
      'Football',        'Laptop',        'Jacket',         'Jeans']
Length: 20, dtype: str

Cleaning Category Column

In [86]:
df["Category"].unique()
#duplicates with other capital and small letters ae removed
same_map={
    "electronic" : "Electronics",
    "ELECTRONICS" : "Electronics",
    "electronics" : "Electronics",
    "sports" : "Sports"
} 

df["Category"]=df["Category"].str.replace(same_map)
print(df["Category"].unique())

<StringArray>
['Home', 'Electronics', 'Sports', 'Books', 'Clothing', 'Electronicss', nan]
Length: 7, dtype: str

In [87]:
# #checking how much % the null values are
print((df["Category"].isna().sum()/len(df))*100)
#filling mode to Category column
df["Category"]=df["Category"].fillna(df["Category"].mode()[0])
print(df["Category"].isnull().sum())
print(df["Category"].dtype)

7.920792079207921
0
str

Cleaning Quantity Column

In [88]:
print(df["Quantity"].dtype)
# #coverting string dtype to integer dtype
df["Quantity"]=pd.to_numeric(df["Quantity"],errors="coerce")
# print(df.info())

#counting the nan values in Quantity column
mask=pd.to_numeric(df["Quantity"],errors="coerce").isna()
print(df.loc[mask,["Quantity"]])

#filling nan values to median of column Quantity
df["Quantity"]=df["Quantity"].fillna(df["Quantity"].median())
print(df["Quantity"].dtype)

print(df.isnull().sum())

print(df["Quantity"].describe())

str
    Quantity
6        NaN
64       NaN
67       NaN
93       NaN
96       NaN
float64
Id                 0
Customer name      0
Order id           0
Order date         0
Product            0
Category           0
Quantity           0
Price              5
Payment method     0
Status             0
Total             13
dtype: int64
count    101.000000
mean       2.930693
std        1.745035
min       -5.000000
25%        2.000000
50%        3.000000
75%        4.000000
max        5.000000
Name: Quantity, dtype: float64

Cleaning Price Column

In [89]:
print(df["Price"].dtype)
#converting datatype from str to numeric datatype
df["Price"]=pd.to_numeric(df["Price"],errors="coerce")
#cheching datatype
print(df["Price"].dtype)

#actual length of column Price
print(len(df["Price"]))
#length of column Price grater than zero
print(len(df["Price"]>0))
#display number of notnull values
print(df["Price"].notna().sum())
#display number of null values
print(df["Price"].isna().sum())
#filling median to null values
df["Price"]=df["Price"].fillna(df["Price"].median())

print(df.isnull().sum())

str
float64
101
101
92
9
Id                 0
Customer name      0
Order id           0
Order date         0
Product            0
Category           0
Quantity           0
Price              0
Payment method     0
Status             0
Total             13
dtype: int64

Cleaning Total Column

In [90]:
print(df)
#filling null values in column Total with (Quantity * Price)
df["Total"]=df["Total"].fillna(df["Quantity"]*df["Price"])
print(df["Total"])

      Id Customer name   Order id Order date        Product     Category  \
0    100  Customer_100  ORD-41285 2024-11-22        Blender         Home
1    101  Customer_101  ORD-35783 2025-07-05     Smartphone  Electronics
2    102  Customer_102  ORD-84355 2024-12-23  Tennis Racket       Sports
3    103  Customer_103  ORD-57811 2025-03-19        Science        Books
4    104  Customer_104  ORD-93614 2025-10-20      Biography        Books
..   ...           ...        ...        ...            ...          ...
98   198  Customer_198  ORD-14608 2025-07-27         Vacuum        Books
99   199  Customer_199  ORD-82922 2025-01-22        Blender         Home
100  175  Customer_175  ORD-56651 2025-02-24     Headphones  Electronics
101  142  Customer_142  ORD-69018 2025-10-30          Shoes     Clothing
102  146  Customer_146  ORD-32755 2025-07-09     Basketball  Electronics

     Quantity    Price    Payment method      Status     Total
0         3.0   38.000  Cash on Delivery     Shipped   114.000
1         2.0  549.275            PayPal  Processing       NaN
2         1.0  389.050            PayPal   Delivered   389.050
3         5.0  233.920            PayPal  Processing  1169.600
4         1.0  552.510  Cash on Delivery  Processing   552.510
..        ...      ...               ...         ...       ...
98        2.0  497.010  Cash on Delivery     Shipped   994.020
99        5.0  372.280       Credit Card     Shipped  1861.400
100       1.0  111.360       Credit Card  Processing    77.952
101       5.0  645.260       Credit Card     Shipped  3226.300
102       2.0  705.420     Bank Transfer  Processing  1410.840

[101 rows x 11 columns]
0       114.000
1      1098.550
2       389.050
3      1169.600
4       552.510
         ...
98      994.020
99     1861.400
100      77.952
101    3226.300
102    1410.840
Name: Total, Length: 101, dtype: float64


Checking Cleaned Dataset

In [91]:
# checing null values
print(df.isnull().sum())

Id                0
Customer name     0
Order id          0
Order date        0
Product           0
Category          0
Quantity          0
Price             0
Payment method    0
Status            0
Total             0
dtype: int64

In [92]:
#checing duplicate values
print(df.duplicated().sum())

#cheching duplicate row
df[df.duplicated(keep=False)]

#deleting duplicate column
df=df.drop_duplicates()
print(df.duplicated().sum())

1
0

In [93]:
#diplaying dataframe
df

,Id,Customer name,Order id,Order date,Product,Category,Quantity,Price,Payment method,Status,Total
0,100,Customer_100,ORD-41285,2024-11-22,Blender,Home,3.0,38.000,Cash on Delivery,Shipped,114.000
1,101,Customer_101,ORD-35783,2025-07-05,Smartphone,Electronics,2.0,549.275,PayPal,Processing,1098.550
2,102,Customer_102,ORD-84355,2024-12-23,Tennis Racket,Sports,1.0,389.050,PayPal,Delivered,389.050
3,103,Customer_103,ORD-57811,2025-03-19,Science,Books,5.0,233.920,PayPal,Processing,1169.600
4,104,Customer_104,ORD-93614,2025-10-20,Biography,Books,1.0,552.510,Cash on Delivery,Processing,552.510
...,...,...,...,...,...,...,...,...,...,...,...
97,197,Customer_197,ORD-79139,2025-06-23,Blender,Home,1.0,160.160,PayPal,Cancelled,160.160
98,198,Customer_198,ORD-14608,2025-07-27,Vacuum,Books,2.0,497.010,Cash on Delivery,Shipped,994.020
99,199,Customer_199,ORD-82922,2025-01-22,Blender,Home,5.0,372.280,Credit Card,Shipped,1861.400
100,175,Customer_175,ORD-56651,2025-02-24,Headphones,Electronics,1.0,111.360,Credit Card,Processing,77.952
101,142,Customer_142,ORD-69018,2025-10-30,Shoes,Clothing,5.0,645.260,Credit Card,Shipped,3226.300

In [94]:
#checking unique values spelling
print(df["Category"].unique())
print(df["Product"].unique())
print(df["Status"].unique())
print(df["Payment method"].unique())

<StringArray>
['Home', 'Electronics', 'Sports', 'Books', 'Clothing', 'Electronicss']
Length: 6, dtype: str
<StringArray>
[      'Blender',    'Smartphone', 'Tennis Racket',       'Science',
     'Biography',    'Basketball',        'Comics',         'Shoes',
       'Fiction',     'Microwave',      'Yoga Mat',        'Vacuum',
          'Lamp',       'T-shirt',    'Smartwatch',    'Headphones',
      'Football',        'Laptop',        'Jacket',         'Jeans']
Length: 20, dtype: str
<StringArray>
['Shipped', 'Processing', 'Delivered', 'Cancelled', 'Returned']
Length: 5, dtype: str
<StringArray>
['Cash on Delivery', 'PayPal', 'Bank Transfer', 'Credit Card']
Length: 4, dtype: str

Full Cleaned Details

In [95]:
print(df)
print(df.info())
print(df.isna().sum())
print(df.describe())

      Id Customer name   Order id Order date        Product     Category  \
0    100  Customer_100  ORD-41285 2024-11-22        Blender         Home
1    101  Customer_101  ORD-35783 2025-07-05     Smartphone  Electronics
2    102  Customer_102  ORD-84355 2024-12-23  Tennis Racket       Sports
3    103  Customer_103  ORD-57811 2025-03-19        Science        Books
4    104  Customer_104  ORD-93614 2025-10-20      Biography        Books
..   ...           ...        ...        ...            ...          ...
97   197  Customer_197  ORD-79139 2025-06-23        Blender         Home
98   198  Customer_198  ORD-14608 2025-07-27         Vacuum        Books
99   199  Customer_199  ORD-82922 2025-01-22        Blender         Home
100  175  Customer_175  ORD-56651 2025-02-24     Headphones  Electronics
101  142  Customer_142  ORD-69018 2025-10-30          Shoes     Clothing

     Quantity    Price    Payment method      Status     Total
0         3.0   38.000  Cash on Delivery     Shipped   114.000
1         2.0  549.275            PayPal  Processing  1098.550
2         1.0  389.050            PayPal   Delivered   389.050
3         5.0  233.920            PayPal  Processing  1169.600
4         1.0  552.510  Cash on Delivery  Processing   552.510
..        ...      ...               ...         ...       ...
97        1.0  160.160            PayPal   Cancelled   160.160
98        2.0  497.010  Cash on Delivery     Shipped   994.020
99        5.0  372.280       Credit Card     Shipped  1861.400
100       1.0  111.360       Credit Card  Processing    77.952
101       5.0  645.260       Credit Card     Shipped  3226.300

[100 rows x 11 columns]
<class 'pandas.DataFrame'>
Index: 100 entries, 0 to 101
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Id              100 non-null    int64
 1   Customer name   100 non-null    str
 2   Order id        100 non-null    str
 3   Order date      100 non-null    datetime64[us]
 4   Product         100 non-null    str
 5   Category        100 non-null    str
 6   Quantity        100 non-null    float64
 7   Price           100 non-null    float64
 8   Payment method  100 non-null    str
 9   Status          100 non-null    str
 10  Total           100 non-null    float64
dtypes: datetime64[us](1), float64(3), int64(1), str(6)
memory usage: 9.4 KB
None
Id                0
Customer name     0
Order id          0
Order date        0
Product           0
Category          0
Quantity          0
Price             0
Payment method    0
Status            0
Total             0
dtype: int64
               Id           Order date    Quantity         Price         Total
count  100.000000                  100  100.000000    100.000000    100.000000
mean   149.610000  2025-04-24 23:16:48    2.940000    612.425450   1336.681050
min    100.000000  2023-01-05 00:00:00   -5.000000   -100.000000 -20000.000000
25%    125.750000  2025-02-09 00:00:00    2.000000    321.740000    655.741000
50%    149.500000  2025-05-18 12:00:00    3.000000    549.275000   1300.930000
75%    174.250000  2025-08-04 00:00:00    4.250000    711.795000   2363.090000
max    199.000000  2025-11-06 00:00:00    5.000000  10000.000000   4722.700000
std     28.597483                  NaN    1.751305    982.025364   2482.309318

Cleaning the negative Rows

In [96]:
print(df["Quantity"].dtype)
# #checking negative values
df[(df["Quantity"]<0) | (df["Price"]<0)]
#removing negative values
df=df[(df["Quantity"]>0) & (df["Price"]>0)]

#checking 
print(df["Quantity"].min())
print(df["Price"].min())
print(df["Total"].min())
print(df["Quantity"]*df["Price"]==df["Total"])

float64
1.0
38.0
40.95
0       True
1       True
2       True
3       True
4       True
       ...
97      True
98      True
99     False
100    False
101     True
Length: 97, dtype: bool

Cleaning Column Total

In [97]:
#correcting "Total" column
df["Total"]=df["Quantity"]*df["Price"]
df["Price"]=df["Price"].round(2)
df["Total"]=df["Total"].round(2)

print(df.isnull().sum())

Id                0
Customer name     0
Order id          0
Order date        0
Product           0
Category          0
Quantity          0
Price             0
Payment method    0
Status            0
Total             0
dtype: int64

In [98]:
df

,Id,Customer name,Order id,Order date,Product,Category,Quantity,Price,Payment method,Status,Total
0,100,Customer_100,ORD-41285,2024-11-22,Blender,Home,3.0,38.00,Cash on Delivery,Shipped,114.00
1,101,Customer_101,ORD-35783,2025-07-05,Smartphone,Electronics,2.0,549.28,PayPal,Processing,1098.55
2,102,Customer_102,ORD-84355,2024-12-23,Tennis Racket,Sports,1.0,389.05,PayPal,Delivered,389.05
3,103,Customer_103,ORD-57811,2025-03-19,Science,Books,5.0,233.92,PayPal,Processing,1169.60
4,104,Customer_104,ORD-93614,2025-10-20,Biography,Books,1.0,552.51,Cash on Delivery,Processing,552.51
...,...,...,...,...,...,...,...,...,...,...,...
97,197,Customer_197,ORD-79139,2025-06-23,Blender,Home,1.0,160.16,PayPal,Cancelled,160.16
98,198,Customer_198,ORD-14608,2025-07-27,Vacuum,Books,2.0,497.01,Cash on Delivery,Shipped,994.02
99,199,Customer_199,ORD-82922,2025-01-22,Blender,Home,5.0,372.28,Credit Card,Shipped,1861.40
100,175,Customer_175,ORD-56651,2025-02-24,Headphones,Electronics,1.0,111.36,Credit Card,Processing,111.36
101,142,Customer_142,ORD-69018,2025-10-30,Shoes,Clothing,5.0,645.26,Credit Card,Shipped,3226.30

In [99]:
df.info()

<class 'pandas.DataFrame'>
Index: 97 entries, 0 to 101
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Id              97 non-null     int64
 1   Customer name   97 non-null     str
 2   Order id        97 non-null     str
 3   Order date      97 non-null     datetime64[us]
 4   Product         97 non-null     str
 5   Category        97 non-null     str
 6   Quantity        97 non-null     float64
 7   Price           97 non-null     float64
 8   Payment method  97 non-null     str
 9   Status          97 non-null     str
 10  Total           97 non-null     float64
dtypes: datetime64[us](1), float64(3), int64(1), str(6)
memory usage: 9.1 KB

In [100]:
df.describe()

,Id,Order date,Quantity,Price,Total
count,97.000000,97,97.000000,97.000000,97.000000
mean,150.237113,2025-04-24 16:04:56.907216,3.072165,523.206804,1640.391959
min,100.000000,2023-01-05 00:00:00,1.000000,38.000000,40.950000
25%,126.000000,2025-02-09 00:00:00,2.000000,336.020000,705.780000
50%,151.000000,2025-05-19 00:00:00,3.000000,549.280000,1461.840000
75%,175.000000,2025-08-03 00:00:00,5.000000,705.420000,2520.250000
max,199.000000,2025-11-06 00:00:00,5.000000,978.630000,4722.700000
std,28.769839,NaN,1.494765,251.378338,1150.039096

Saving dataframe to "cleaned_sales_data.csv"

In [101]:
df.to_csv("cleaned_sales_data.csv",index=False)